### ISSUE TITLE
creature_text

### ISSUE THREAD

**Issue by yolinlin** [keyshuwen/wow_db_chinese#1]
creature_text表还有groupid和ID，只是UPDATE creature_text SET text='库卡隆，行动！勇士们，提高警惕！天灾军团已经...' WHERE entry=37187;这样写的话，所有37187都是同一句话。BUG……

**Comment by keyshuwen** [comment]
@yolinlin 现在在做。DB_1.12.3的汉化项目。有兴趣可以一起。 谢谢提醒。
